---
title: "Gaze-xsit Looking Animation"
author: "Kyle MacDonald"
output: html_document
---

```{r chunk opts}
rm(list = ls())
knitr::opts_chunk$set(echo=T, warning=F, cache=F, message=F, sanitize = T)
source("../helper_functions/helper_functions.R")
```

Read data.

```{r}
d_time <- read_csv("../../data/3_tidy_data/gaze_xsit_tidy_timecourse.csv")
```


```{r}
d_plot <- d_time %>%
  filter(t.stim > 0, t.stim <= 4,
         trial_num != "fam", trial.type != "familiar")
```

## Make the animation of looking behavior unfolding over time

TODO: get the stimuli images on the plot. 

```{r}
library(gganimate)
library(png)
library(grid)
```

```{r}
img <- readPNG("stim.png")
g <- rasterGrob(img, interpolate=TRUE, width = unit(1,"npc"), 
                               height = unit(1,"npc"))
```

```{r}
p <- d_plot %>% 
  filter(subid == subid[3], trial_num == "1", trial.type == "exposure",
         t.stim <= 5) %>% 
  ggplot(aes(x = x, y = y, frame = t.stim)) +
  #annotation_custom(g, xmin=-Inf, xmax=Inf, ymin=-Inf, ymax=Inf) +
  geom_path(aes(cumulative = TRUE), color = "darkgrey") +
  geom_point(aes(cumulative = TRUE), shape = 21, size = 5, color = "black",
             fill = "darkorange", size = 5, stroke = 1, alpha = 0.4) +
  guides(color = F) + 
  xlim(0,1980) +
  ylim(0, 1020)
p
```

```{r}
gganimate(p, interval = .15)
```

```{r}
gganimate(p, interval = .15, "output.gif")
```

